### PR TITLE
Update AA version dependency

### PR DESCRIPTION
**Pull request by dkniffin**

### CODE REVIEW

**Comment by dkniffin** [comment]
@blocknotes Any chance you can merge this and bump the gem version?

**Comment by dkniffin** [comment]
Or, if it's easier, I'd be happy to be added as a contributor to it and do it myself.

**Comment by blocknotes** [comment]
Thank you @dkniffin

**Comment by dkniffin** [comment]
Thanks @blocknotes! Also, the offer still stands if you wan any help maintaining this. I'm using it a bit on a project, so if I run into any other issues, I'll probably put up another PR. But so far, it's a nice gem. Great work!

**Pull request merged**
