### PR TITLE
v1.0.0

### PR DESCRIPTION
**Pull request by blocknotes**
- Add Not operator
- Use `args` attribute for actions' arguments
- Update `callback` action to have the first parameter el

### CODE REVIEW

**Comment by tracyloisel** [comment]
do you want to merge it my friend ?

**Comment by blocknotes** [comment]
Ehi @tracyloisel - I'm going to split this PR in smaller ones.
This one will be removed

**Comment by tracyloisel** [comment]
Ok cool. If I can help let me know.
I am in need for a success callback in in-line edition and I plan to open a
PR soon 🙏🏼

**Comment by blocknotes** [comment]
> Ok cool. If I can help let me know. I am in need for a success callback in in-line edition and I plan to open a PR soon 🙏🏼

If you like start opening an issue to evaluate if it fits in the project of if it works better in a personal fork.

**Comment by blocknotes** [comment]
Splitted in 3 PRs:

- #18 
- #19 
- #20 

Closing.

**Pull request closed without merging**
